### ISSUE TITLE
Support vertical preview panel right to content pane

### ISSUE THREAD

**Issue by nerk** [asciidoctor/brackets-asciidoc-preview#10]
Vertical preview panel right to the content pane uses available screen space much better.

**Comment by nerk** [comment]
As of 1.1.3, it is now possible to detach the preview pane from the editor into a separate window. This is  extremely useful with a second monitor. Implementing a vertical panel next to the editor pane is still not officially supported and will definitely cause conflicts with other extensions trying to do the same.

**Comment by mojavelinux** [comment]
Cool!

**Comment by nerk** [comment]
Closing the issue. Brackets still does not really provide a clean way to implement extensions with a vertical window. Using a detached preview pane should be good enough for now.

**Comment by anidotnet** [comment]
Any update on it yet?

**Comment by nerk** [comment]
Unfortunately, I did not find a good way in Barckets to implement this and therefore gave up on this. However, you can just detach the bottom pane and use the detached window by placing it right or left the of Brackets editor window.
