### ISSUE TITLE
How to export to PDF

### ISSUE THREAD

**Issue by gembin** [asciidoctor/brackets-asciidoc-preview#23]
Anyway to export a adoc to PDF ?

**Comment by nerk** [comment]
Use the export button (box with curved arrow) to display the document in a browser. From there, you can print or save as PDF. Direkt generation of PDF is a bit out of scope for the previewer.

**Comment by nerk** [comment]
However, if you really want to create a full-featured PDF the official asciidoctor toolchain should be used instead.

**Comment by gembin** [comment]
Ok, got it.  thanks nerk!
