### ISSUE TITLE
Sync from preview pane to edit pane, instead of vice versa?

### ISSUE THREAD

**Issue by stallio** [asciidoctor/brackets-asciidoc-preview#24]
Currently there are features that allow you to sync the preview pane with the part of the document you are currently editing.

It would be great if there were a similar feature that would sync the editing pane with the currently-viewed section of the preview pane. This would be handy for reviewing documents -- for example if you spot a mistake in the preview pane then you could easily jump to that spot and fix it.

**Comment by nerk** [comment]
This feature is now implemented. You may click into the preview pane while holding down the CTRL key.

**Comment by mojavelinux** [comment]
Wow! So cool!
