### ISSUE TITLE
Code listing CSS bug in some themes when source type is unrecognized

### ISSUE THREAD

**Issue by stallio** [asciidoctor/brackets-asciidoc-preview#30]
The cerulean and slate themes have a bunch of CSS like this:

```
.listingblock:hover code.asciidoc:before {
  content: "asciidoc";
}
```

But if I set my source to a value other than the ones that are listed, like so:

```
[source,foo,numbered]
.First Foo app
---------------------------------------
begin Foo;
if foo && bar
```

Then when I hover my mouse over the listing in the preview window, it inserts the name of the language it thinks I'm using in front of the code. In this screenshot it thinks I'm using Ruby:

![screenshot 1182](https://cloud.githubusercontent.com/assets/6136277/9669068/02f974d0-5253-11e5-95fa-3af2cfd66e9b.png)

This also happens if I set my source to `html` though in that case it tells me I'm using XML:

![screenshot 1183](https://cloud.githubusercontent.com/assets/6136277/9669162/7a5c8404-5253-11e5-8b09-3271bd3cc4fd.png)

**Comment by nerk** [comment]
I tried this with Cerulean, Slate, and Github themes and your example listing. Works for me. Could you please give more details regarding exact versions of Brackets and this plugin you are using?

**Comment by stallio** [comment]
Sorry, I truncated the code for the sake of posting it here, but the bug doesn't happen with the abbreviated code.  Here's the full code:

```
[source,foo,numbered]
.First Foo app
---------------------------------------
begin Foo;
if foo && bar                       
   then
     if foobar == true
     output foo
   else
     if foobar == maybe
     output foo
   else
     if foobar == unknowable
       output foo
   else
     output bar
for each Foo
   print 'foo'                      
   next;
end Foo.                            
---------------------------------------
```

I'm using
Brackets Release 1.4 build 1.4.0-16380 (release 273804eb3) 
asciidoc-preview 1.1.6
