### ISSUE TITLE
Enhancement : Ability to use a custom theme

### ISSUE THREAD

**Issue by JBR69** [asciidoctor/brackets-asciidoc-preview#34]
Hi,

It would be interesting to use its own theme in the previewer (and that it is not removed during an update).
Currently, I added my CSS in the `themes `directory and I modified the file `templates/settings.html` to see it in the listbox ; but in the next update, I had to do the same thing :-(

Jérôme

**Comment by nerk** [comment]
Hmm, maybe a separate directory which is being scanned?

**Comment by JBR69** [comment]
or why don't use the attributes `:stylesdir:` and `:stylesheet:` to get the CSS of the document ?

**Comment by mojavelinux** [comment]
The stylesheet attribute is intended for standalone documents (and has to worry about a lot more than just the inner content of the page). Having said that, it would be interesting to honor an `embeddable-stylesheet` (or similar) attribute.

**Comment by nerk** [comment]
Custom themes can now be installed (see updated README).
