### ISSUE TITLE
Vertical Split

### ISSUE THREAD

**Issue by abradshaw** [asciidoctor/brackets-asciidoc-preview#38]
Enable the ability t p do a vertical split as well as the default horizontal one

**Comment by nerk** [comment]
I investigated this a while ago. As far as I know, this is not easily possible with current versions of Brackets. There is no official way for plugins to create a vertical split pane. All existing plugins doing something like this are not really compatible with other plugins trying to do the same. 
The best option might be trying to use the split-view mode and use one of the panes as a preview pane.

For now, you can already detach the preview pane  (the two squares in the upper right corner) into a separate window to achieve something very similar. I am using this all the time.

**Comment by abradshaw** [comment]
Ok, thats a good idea, Thanks
